org: dpsingh77
app: aws-api-http
service: aws-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  api:
    handler: hello.handler
    events:
      - httpApi:
          path: /hello
          method: get
  api-bye:
    handler: bye.handler
    events:
      - httpApi:
          path: /bye
          method: get
